<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Создать обращение и$APPLICATION->IncludeComponent(
	"api:main.feedback", 
	".default", 
	array(
		"ADMIN_EVENT_MESSAGE_ID" => array(
			0 => "33",
		),
		"AGREEMENT_ERROR" => "Пожалуйста, ознакомьтесь с условиями подачи обращения",
		"AGREEMENT_LINK" => "/appeal/o-personalnykh-dannykh.php",
		"AGREEMENT_TEXT" => "Я принимаю ответственность за правильность предоставленных персональных данных и даю согласие на их обработку",
		"AJAX_MODE" => "Y",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "Y",
		"AJAX_OPTION_STYLE" => "Y",
		"BCC" => "",
		"BRANCH_ACTIVE" => "N",
		"BUTTON_TEXT_BEFORE" => "",
		"CHOOSE_FILE_TEXT" => "Выбрать файл",
		"COUNT_INPUT_FILE" => "1",
		"CSS_MODAL_CONTENT" => "Модуль <b>Форма обратной связи + конструктор форм</b> предназначен для отправки сообщений с сайта.<br>Отличается от стандартных форм удобством в использовании и гибкой настройкой, отправкой файлов вложениями или ссылками на файл, скрытой защитой от спама, работой нескольких форм на одной странице, встроенным валидатором форм, красивым шаблоном css-фреймворка Uikit, очень функциональным конструктором форм, записью сообщений в инфоблок и мн. другими функциями, которые очень необходимы на каждом сайте.",
		"CSS_MODAL_FOOTER" => "",
		"CSS_MODAL_HEADER" => "Создание обращения ",
		"CUSTOM_FIELDS" => array(
			0 => "Выберите орган или должностное лицо, которому адресовано Ваше обращение@select@name=ORGAN@values=Администрация Майминского сельского поселения#Глава Майминского сельского поселения#Сельский Совет депутатов Майминского сельского поселения@checked=Администрация Майминского сельского поселения@required@sort=1",
			1 => "Ваша Фамилия@input@type=text@name=FAMILY@value=Например, Иванов@required@data-validation=[FAMILY]@data-validation-label=Ваша Фамилия@tooltip-title=Ваше имя@sort=2",
			2 => "Ваше Имя@input@type=text@name=NAME@value=Например, Иван@required@data-validation=[NAME]@data-validation-label=Ваше Имя@tooltip-title=Ваше имя@sort=3",
			3 => "Ваше Отчество (при наличии)@input@type=text@name=OTCH@value=Например, Иван@data-validation=[OTCH]@data-validation-label=Ваше отчество@tooltip-title=Ваше отчество (при наличии)@sort=4",
			4 => "Ваш E-mail@input@type=text@name=EMAIL@required@data-validation=[EMAIL]@data-validation-label=Ваш E-mail@data-inputmask='alias': 'email'@sort=5",
			5 => "Номер телефона@input@type=text@name=PHONE@data-validation=[PHONE]@data-validation-label=Номер телефона@sort=6",
			6 => "<em>В соответствии с частью 1 статьи 7 Федерального закона от 2 мая 2006 года № 59-ФЗ «О порядке рассмотрения обращений граждан Российской Федерации» гражданин в своём обращении в обязательном порядке излагает суть предложения, заявления или жалобы.<br>Обращаем Ваше внимание, что в целях объективного и всестороннего рассмотрения Вашего обращения в установленные сроки необходимо в тексте обращения указывать адрес описанного Вами места действия, факта или события.<br>В случае, если текст Вашего обращения не позволяет определить суть предложения, заявления или жалобы, ответ на обращение не дается и оно не&nbsp;подлежит направлению на рассмотрение в государственный орган, орган местного самоуправления или должностному лицу, в соответствии с их компетенцией, о чем Вам будет сообщено в&nbsp;течение семи дней со дня регистрации обращения. <br> Обращаем Ваше внимание, что при написании текста обращения в форме электронного документа в поле ввода текста обращения в форме электронного документа для изложения сути предложения, заявления или жалобы отсутствует ограничение по вводимому количеству символов.</em>",
			7 => "Текст обращения@textarea@name=TEXT@cols=70@rows=5@required@sort=7",
			8 => "<em>В случае необходимости в подтверждение своих доводов гражданин вправе приложить к обращению необходимые документы и материалы в электронной форме, воспользовавшись функцией «Прикрепить файл».  Обращаем внимание, что прикрепляемые в предложенном на сайте формате документы и материалы служат лишь подтверждением доводов автора обращения, изложенных в тексте обращения.  Приложить необходимые документы и материалы в электронной форме можно в любой последовательности двумя самостоятельными вложениями файла без архивирования (файл вложения) по одному из двух разных типов допустимых форматов: текстового (графического) формата: txt, doc, docx, rtf, xls, xlsx, pps, ppt, odt, ods, odp, pub, pdf, jpg, jpeg, bmp, png, tif, gif, pcx; аудио- (видео-) формата: mp3, wma, avi, mp4, mkv, wmv, mov, flv. Иные форматы не обрабатываются в информационных системах Администрации Майминского сельского поселения.</em>",
			9 => "",
		),
		"DATETIME" => "",
		"DEFAULT_OPTION_TEXT" => "-- Выбрать --",
		"DELETE_FILES_AFTER_UPLOAD" => "N",
		"DIR_URL" => "",
		"DISABLE_SEND_MAIL" => "N",
		"DISPLAY_FIELDS" => array(
		),
		"EMAIL_ERROR_MESS" => "Указанный E-mail некорректен",
		"EMAIL_TO" => "mail@maima-sp.ru",
		"FIELD_BORDER_ACTIVE" => "",
		"FIELD_BOX_SHADOW_ACTIVE" => "",
		"FIELD_ERROR_MESS" => "#FIELD_NAME# обязательное",
		"FIELD_NAME_POSITION" => "stacked",
		"FIELD_SIZE" => "default",
		"FILE_DESCRIPTION" => array(
			0 => "Приложите файл",
			1 => "",
		),
		"FILE_ERROR_MESS" => "Все файлы обязательные",
		"FILE_EXTENSIONS" => "txt, doc, docx, rtf, xls, xlsx, pps, ppt, odt, ods, odp, pub, pdf, jpg, jpeg, bmp, png, tif, gif, pcx, mp3, wma, avi, mp4, mkv, wmv, mov, flv",
		"FORM_AUTOCOMPLETE" => "Y",
		"FORM_CLASS" => "",
		"FORM_FIELD_WIDTH" => "100%",
		"FORM_LABEL_TEXT_ALIGN" => "left",
		"FORM_LABEL_WIDTH" => "0",
		"FORM_SUBMIT_CLASS" => "uk-button",
		"FORM_SUBMIT_STYLE" => "",
		"FORM_SUBMIT_VALUE" => "Подать обращение",
		"FORM_TEXT_AFTER" => "",
		"FORM_TEXT_BEFORE" => "",
		"FORM_TITLE" => "Создание обращения",
		"FORM_TITLE_LEVEL" => "2",
		"HIDE_ASTERISK" => "N",
		"HIDE_FIELD_NAME" => "N",
		"HIDE_FORM_AFTER_SEND" => "Y",
		"IBLOCK_ELEMENT_ACTIVE" => "Y",
		"IBLOCK_ID" => "12",
		"IBLOCK_TYPE" => "forms",
		"ICHECK_THEME" => "flat",
		"ICHECK_THEME_COLOR" => "blue",
		"INCLUDE_AUTOSIZE" => "Y",
		"INCLUDE_CHOSEN" => "Y",
		"INCLUDE_CSSMODAL" => "uikit2",
		"INCLUDE_ICHECK" => "Y",
		"INCLUDE_INPUTMASK" => "Y",
		"INCLUDE_JQUERY" => "jquery2",
		"INCLUDE_PLACEHOLDER" => "N",
		"INCLUDE_TOOLTIPSTER" => "N",
		"INCLUDE_VALIDATION" => "Y",
		"INSTALL_IBLOCK" => "N",
		"MAX_FILE_SIZE" => "31457280",
		"MODAL_BUTTON_CLASS" => "uk-button uk-button-danger",
		"MODAL_BUTTON_HTML" => "Подать обращение",
		"MODAL_FOOTER_HTML" => "",
		"MODAL_HEADER_HTML" => "Подать обращение",
		"MODAL_WIDTH" => "",
		"OK_TEXT" => "Ваше обращение успешно отправлено! Уведомление об отправке направлено на адрес электронной почты, указанный в обращении.",
		"OK_TEXT_AFTER" => "",
		"PAGE_TITLE" => "",
		"PAGE_URI" => "",
		"PAGE_URL" => "",
		"REDIRECT_PAGE" => "",
		"REPLACE_FIELD_FROM" => "Y",
		"REQUEST_VARS" => array(
			0 => "",
			1 => "",
		),
		"REQUIRED_FIELDS" => array(
		),
		"SCROLL_TO_FORM_IF_MESSAGES" => "N",
		"SCROLL_TO_FORM_SPEED" => "1000",
		"SEND_ATTACHMENT" => "Y",
		"SERVER_VARS" => array(
			0 => "",
			1 => "",
		),
		"SET_ATTACHMENT_REQUIRED" => "N",
		"SHOW_ATTACHMENT_EXTENSIONS" => "N",
		"SHOW_CSS_MODAL_AFTER_SEND" => "Y",
		"SHOW_FILES" => "Y",
		"SUBJECT" => "",
		"TEMPLATE_STYLE" => "bootstrap3",
		"TITLE_DISPLAY" => "N",
		"TOOLTIPSTER_OPTIONS" => array(
			0 => "animation: 'fade'",
			1 => "delay: 200",
			2 => "theme: 'tooltipster-punk'",
			3 => "contentCloning: true",
			4 => "//trigger: 'click'",
			5 => "",
		),
		"UNIQUE_FORM_ID" => "form6",
		"UPLOAD_FOLDER" => "/upload/feedback",
		"USER_AUTHOR_ADRESS" => "",
		"USER_AUTHOR_CITY" => "",
		"USER_AUTHOR_EMAIL" => "",
		"USER_AUTHOR_FAX" => "",
		"USER_AUTHOR_FIO" => "",
		"USER_AUTHOR_ICQ" => "",
		"USER_AUTHOR_LAST_NAME" => "",
		"USER_AUTHOR_MAILBOX" => "",
		"USER_AUTHOR_MESSAGE" => "",
		"USER_AUTHOR_MESSAGE_THEME" => "",
		"USER_AUTHOR_NAME" => "",
		"USER_AUTHOR_NOTES" => "",
		"USER_AUTHOR_PERSONAL_MOBILE" => "",
		"USER_AUTHOR_PERSONAL_PHONE" => "",
		"USER_AUTHOR_POSITION" => "",
		"USER_AUTHOR_PROFESSION" => "",
		"USER_AUTHOR_SECOND_NAME" => "",
		"USER_AUTHOR_SKYPE" => "",
		"USER_AUTHOR_STATE" => "",
		"USER_AUTHOR_STREET" => "",
		"USER_AUTHOR_WORK_CITY" => "",
		"USER_AUTHOR_WORK_COMPANY" => "",
		"USER_AUTHOR_WORK_MAILBOX" => "",
		"USER_AUTHOR_WORK_PHONE" => "",
		"USER_AUTHOR_WORK_WWW" => "",
		"USER_AUTHOR_WWW" => "",
		"USER_EVENT_MESSAGE_ID" => array(
			0 => "34",
		),
		"USE_AGREEMENT" => "Y",
		"USE_CAPTCHA" => "N",
		"USE_HIDDEN_PROTECTION" => "Y",
		"USE_YM_GOALS" => "N",
		"UUID_LENGTH" => "10",
		"UUID_PREFIX" => "",
		"VALIDATION_MESSAGES" => array(
			0 => "'default':'\$ содержит ошибки'",
			1 => "'NOTEMPTY':'\$ обязательно'",
			2 => "'INTEGER':'\$ должно быть целым числом'",
			3 => "'NUMERIC':'\$ должно быть числом'",
			4 => "'MIXED':'\$ должно содержать буквы или цифры (без спец. символов).'",
			5 => "'NAME':'\$ неверного формата'",
			6 => "'NOSPACE':'\$ не должно содержать пробелы'",
			7 => "'TRIM':'\$ не должно начинаться или заканчиваться пробелом'",
			8 => "'DATE':'\$ содержит недопустимый формат YYYY-MM-DD'",
			9 => "'EMAIL':'\$ неверного формата'",
			10 => "'URL':'\$ неверного формата'",
			11 => "'PHONE':'\$ неверного формата'",
			12 => "'<':'\$ должно быть меньше % символов'",
			13 => "'<=':'\$ должно быть меньше или равно % символам'",
			14 => "'>':'\$ должно быть больше % символов.'",
			15 => "'>=':'\$ должно быть больше или равно % символам'",
			16 => "'==':'\$ должно быть равно % символам'",
			17 => "'!=':'\$ должно быть не равно % символам'",
			18 => "",
		),
		"WRITE_MESS_DIV_STYLE" => "padding:5px;border-bottom:1px dashed #dadada;",
		"WRITE_MESS_DIV_STYLE_NAME" => "font-weight:bold;",
		"WRITE_MESS_DIV_STYLE_VALUE" => "",
		"WRITE_MESS_FILDES_TABLE" => "Y",
		"WRITE_MESS_TABLE_STYLE" => "font-family: Open Sans,Tahoma,Arial,sans-serif; font-size: 13px; border-collapse:collapse; border-spacing:0;",
		"WRITE_MESS_TABLE_STYLE_NAME" => "border: 1px solid #e0e0e0; border-left-color:#fff; padding: 5px 15px 5px 0px; vertical-align: middle;",
		"WRITE_MESS_TABLE_STYLE_VALUE" => "border: 1px solid #e0e0e0; border-right-color:#fff; padding: 5px 15px 5px 10px; vertical-align: middle;",
		"WRITE_ONLY_FILLED_VALUES" => "Y",
		"YM_COUNTER_ID" => "",
		"YM_TARGET_ID" => "",
		"YM_TARGET_NAME" => "",
		"COMPONENT_TEMPLATE" => ".default"
	),
	false
);" => "N",
		"TOOLTIPSTER_OPTIONS" => array(0=>"animation: 'fade'",1=>"delay: 200",2=>"theme: 'tooltipster-punk'",3=>"contentCloning: true",4=>"//trigger: 'click'",5=>"",),
		"UNIQUE_FORM_ID" => "form6",
		"UPLOAD_FOLDER" => "/upload/feedback",
		"USER_AUTHOR_ADRESS" => "",
		"USER_AUTHOR_CITY" => "",
		"USER_AUTHOR_EMAIL" => "",
		"USER_AUTHOR_FAX" => "",
		"USER_AUTHOR_FIO" => "",
		"USER_AUTHOR_ICQ" => "",
		"USER_AUTHOR_LAST_NAME" => "",
		"USER_AUTHOR_MAILBOX" => "",
		"USER_AUTHOR_MESSAGE" => "",
		"USER_AUTHOR_MESSAGE_THEME" => "",
		"USER_AUTHOR_NAME" => "",
		"USER_AUTHOR_NOTES" => "",
		"USER_AUTHOR_PERSONAL_MOBILE" => "",
		"USER_AUTHOR_PERSONAL_PHONE" => "",
		"USER_AUTHOR_POSITION" => "",
		"USER_AUTHOR_PROFESSION" => "",
		"USER_AUTHOR_SECOND_NAME" => "",
		"USER_AUTHOR_SKYPE" => "",
		"USER_AUTHOR_STATE" => "",
		"USER_AUTHOR_STREET" => "",
		"USER_AUTHOR_WORK_CITY" => "",
		"USER_AUTHOR_WORK_COMPANY" => "",
		"USER_AUTHOR_WORK_MAILBOX" => "",
		"USER_AUTHOR_WORK_PHONE" => "",
		"USER_AUTHOR_WORK_WWW" => "",
		"USER_AUTHOR_WWW" => "",
		"USER_EVENT_MESSAGE_ID" => array("34"),
		"USE_AGREEMENT" => "Y",
		"USE_CAPTCHA" => "Y",
		"USE_HIDDEN_PROTECTION" => "Y",
		"USE_YM_GOALS" => "N",
		"UUID_LENGTH" => "10",
		"UUID_PREFIX" => "",
		"VALIDATION_MESSAGES" => array("'default':'\$ содержит ошибки'","'NOTEMPTY':'\$ обязательно'","'INTEGER':'\$ должно быть целым числом'","'NUMERIC':'\$ должно быть числом'","'MIXED':'\$ должно содержать буквы или цифры (без спец. символов).'","'NAME':'\$ неверного формата'","'NOSPACE':'\$ не должно содержать пробелы'","'TRIM':'\$ не должно начинаться или заканчиваться пробелом'","'DATE':'\$ содержит недопустимый формат YYYY-MM-DD'","'EMAIL':'\$ неверного формата'","'URL':'\$ неверного формата'","'PHONE':'\$ неверного формата'","'<':'\$ должно быть меньше % символов'","'<=':'\$ должно быть меньше или равно % символам'","'>':'\$ должно быть больше % символов.'","'>=':'\$ должно быть больше или равно % символам'","'==':'\$ должно быть равно % символам'","'!=':'\$ должно быть не равно % символам'",""),
		"WRITE_MESS_DIV_STYLE" => "padding:5px;border-bottom:1px dashed #dadada;",
		"WRITE_MESS_DIV_STYLE_NAME" => "font-weight:bold;",
		"WRITE_MESS_DIV_STYLE_VALUE" => "",
		"WRITE_MESS_FILDES_TABLE" => "Y",
		"WRITE_MESS_TABLE_STYLE" => "font-family: Open Sans,Tahoma,Arial,sans-serif; font-size: 13px; border-collapse:collapse; border-spacing:0;",
		"WRITE_MESS_TABLE_STYLE_NAME" => "border: 1px solid #e0e0e0; border-left-color:#fff; padding: 5px 15px 5px 0px; vertical-align: middle;",
		"WRITE_MESS_TABLE_STYLE_VALUE" => "border: 1px solid #e0e0e0; border-right-color:#fff; padding: 5px 15px 5px 10px; vertical-align: middle;",
		"WRITE_ONLY_FILLED_VALUES" => "Y",
		"YM_COUNTER_ID" => "",
		"YM_TARGET_ID" => "",
		"YM_TARGET_NAME" => ""
	)
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>
